### ISSUE TITLE
manage versions?

### ISSUE THREAD

**Issue by tomdavidson** [Banno/asdf-hashicorp#1]
Hello, what do you think about managing versions and not only installing, such as rbenv, tfenv, nvm, etc?

**Comment by rubbish** [comment]
@tomdavidson This is mean to be used as a plugin with https://github.com/asdf-vm/asdf. `asdf` handles managing versions with a `.tool-versions` file. I think that answers your question, please let me know if it doesn't.

**Comment by tomdavidson** [comment]
Thank you and sorry - I had looked at the scripts did not realize the grander ecosystem. Using it now!
