### ISSUE TITLE
Error while trying to install vagrant-libvirt

### ISSUE THREAD

**Issue by stormwatch** [Banno/asdf-hashicorp#19]
running
`CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64" vagrant plugin install vagrant-libvirt`

yields
```
(...)
domain.c: En la función ‘ruby_libvirt_domain_init’:                                                                                                            
domain.c:5760:29: error: ‘VIR_DOMAIN_QEMU_AGENT_COMMAND_BLOCK’ (...)
```
while attempting to build ~/.vagrant.d/gems/2.6.2/gems/ruby-libvirt-0.7.1/ext/libvirt ruby-libvirt, Maybe beacuse the system installed libvirt (6.6.0, fedora 33) is not compatible?

Any help, comments, suggestions are welcome.

Thank you

**Comment by DustinChaloupka** [comment]
Looks like you may have created this issue on the wrong repository?

**Comment by stormwatch** [comment]
Maybe? Thanks for the answer nevertheless. The thing is, the command `CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64" vagrant plugin install vagrant-libvirt` runs successfully if I use the upstream Vagrant package installed under /opt and applying the [known workarounds for it to work with Fedora and Similar distributions](https://github.com/vagrant-libvirt/vagrant-libvirt#additional-notes-for-fedora-and-similar-linux-distributions)

**Comment by DustinChaloupka** [comment]
I think I would suggest either the `vagrant` or `vagrant-libvirt` repositories, since it is dealing with those specifically. This repository, while admittedly generalizes to hashicorp, has not been tested to work with `vagrant` or any plugins that `vagrant` might use.
