### ISSUE TITLE
Mangled release names break asdf terraform plugin

### ISSUE THREAD

**Issue by kadrach** [Banno/asdf-hashicorp#3]
Looks like Hashicorp mangled their terraform artifact names. Starting with `0.12.0-alpha3`, the naming convention is now `terraform_0.12.0-alpha4_terraform_0.12.0-alpha4_linux_amd64.zip`, e.g. see [here](https://releases.hashicorp.com/terraform/0.12.0-alpha4/).

**Comment by kadrach** [comment]
```
% asdf install terraform 0.12.0-alpha4                                                                                                          
Downloading terraform version 0.12.0-alpha4 from https://releases.hashicorp.com/terraform/0.12.0-alpha4/terraform_0.12.0-alpha4_linux_amd64.zip
Error: terraform version 0.12.0-alpha4 not found
```

**Comment by djgoku** [comment]
@kadrach https://github.com/hashicorp/terraform/issues/19588
