### ISSUE TITLE
Support terraform 0.12

### ISSUE THREAD

**Issue by johnnyplaydrums** [Banno/asdf-hashicorp#5]
Now that terraform 0.12 has been released, it would be awesome if this plugin could support it! If no one else has the time I can give it a shot, but I figured someone else who as already contributed to this repo could knock it out faster ❤️ 

```
$ asdf install terraform 0.12                                                                                                                                                    
$ Downloading terraform version 0.12 from https://releases.hashicorp.com/terraform/0.12/terraform_0.12_darwin_amd64.zip
Error: terraform version 0.12 not found
```

We would need the url to be `https://releases.hashicorp.com/terraform/0.12.0/terraform_0.12.0_darwin_amd64.zip`

Thank you!

**Comment by rubbish** [comment]
Try `asdf install terraform 0.12.0`, the version from https://www.terraform.io/downloads.html is 0.12.0. I'm hesitant to support `0.12` to be the newest 0.12, but I don't know what other asdf plugins do for this situation.

**Comment by johnnyplaydrums** [comment]
Ah, duh. Thank you! 😄
